In [19]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [20]:
dataset = pd.read_csv('HeartAttack_DataSet_Comma.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [21]:
print(X)

[[63 'Male' 'Asymptomatic' ... 'Upsloping' 0 'Normal']
 [37 'Male' 'Non-anginal pain' ... 'Upsloping' 0 'Fixed defect']
 [41 'Female' 'Atypical Angina' ... 'Downsloping' 0 'Fixed defect']
 ...
 [68 'Male' 'Typical Angina' ... 'Flat' 2 'Reversable defect']
 [57 'Male' 'Typical Angina' ... 'Flat' 1 'Reversable defect']
 [57 'Female' 'Atypical Angina' ... 'Flat' 1 'Fixed defect']]


In [22]:
print(y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0]


In [23]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,1] = le.fit_transform(X[:,1])

In [24]:
print(X)

[[63 1 'Asymptomatic' ... 'Upsloping' 0 'Normal']
 [37 1 'Non-anginal pain' ... 'Upsloping' 0 'Fixed defect']
 [41 0 'Atypical Angina' ... 'Downsloping' 0 'Fixed defect']
 ...
 [68 1 'Typical Angina' ... 'Flat' 2 'Reversable defect']
 [57 1 'Typical Angina' ... 'Flat' 1 'Reversable defect']
 [57 0 'Atypical Angina' ... 'Flat' 1 'Fixed defect']]


In [26]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [2, 6, 10, 12])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))


In [27]:
print(X)

[[1.0 0.0 0.0 ... 0 2.3 0]
 [0.0 1.0 1.0 ... 0 3.5 0]
 [1.0 0.0 0.0 ... 0 1.4 0]
 ...
 [1.0 0.0 1.0 ... 0 3.4 2]
 [1.0 0.0 1.0 ... 1 1.2 1]
 [1.0 0.0 0.0 ... 0 0.0 1]]


In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [30]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [32]:
ann = tf.keras.models.Sequential()


In [33]:
ann.add(tf.keras.layers.Dense(units = 7, activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 7, activation = 'relu'))

In [34]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

In [35]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [36]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
8/8 [==============================] - 0s 2ms/step - loss: 0.7199 - accuracy: 0.5083
Epoch 2/100
8/8 [==============================] - 0s 1ms/step - loss: 0.6924 - accuracy: 0.5785
Epoch 3/100
8/8 [==============================] - 0s 1ms/step - loss: 0.6698 - accuracy: 0.6198
Epoch 4/100
8/8 [==============================] - 0s 1ms/step - loss: 0.6489 - accuracy: 0.6488
Epoch 5/100
8/8 [==============================] - 0s 1ms/step - loss: 0.6315 - accuracy: 0.6777
Epoch 6/100
8/8 [==============================] - 0s 1ms/step - loss: 0.6159 - accuracy: 0.6860
Epoch 7/100
8/8 [==============================] - 0s 2ms/step - loss: 0.6019 - accuracy: 0.7066
Epoch 8/100
8/8 [==============================] - 0s 1ms/step - loss: 0.5877 - accuracy: 0.7314
Epoch 9/100
8/8 [==============================] - 0s 1ms/step - loss: 0.5746 - accuracy: 0.7562
Epoch 10/100
8/8 [==============================] - 0s 1ms/step - loss: 0.5616 - accuracy: 0.7686
Epoch 11/100
8/8 [===========

In [37]:
y_pred = ann.predict(X_test)
print(y_pred)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred), 1),y_test.reshape(len(y_test),1)), axis = 0))
print(np.concatenate((y_pred.reshape(len(y_pred), 1),y_test.reshape(len(y_test),1)), axis = 1))

[[1.7753315e-01]
 [4.2029205e-01]
 [4.3343791e-01]
 [1.2018323e-02]
 [1.9920313e-01]
 [1.4453176e-01]
 [5.3759754e-02]
 [3.2724261e-02]
 [1.3783574e-04]
 [5.5906177e-04]
 [7.2996956e-01]
 [9.3234766e-01]
 [1.5876323e-02]
 [9.2250013e-01]
 [9.4487107e-01]
 [6.5102434e-01]
 [8.9318454e-03]
 [9.5157850e-01]
 [1.7407566e-02]
 [6.5512037e-01]
 [9.1462046e-01]
 [1.3165364e-01]
 [4.4892758e-02]
 [9.3524128e-02]
 [9.3696427e-01]
 [5.7228535e-01]
 [6.0843825e-02]
 [1.6643831e-01]
 [9.7567809e-01]
 [8.1078994e-01]
 [8.2568216e-01]
 [1.1210442e-03]
 [9.7756994e-01]
 [7.1171808e-01]
 [9.6941340e-01]
 [4.4801903e-01]
 [1.9669479e-01]
 [9.7141182e-01]
 [8.5428387e-02]
 [1.7999357e-01]
 [2.9731405e-01]
 [8.2331610e-01]
 [9.1826504e-01]
 [8.4144086e-02]
 [4.0452188e-01]
 [8.5607314e-01]
 [9.5606345e-01]
 [6.7316568e-01]
 [4.0630400e-03]
 [8.6494470e-01]
 [9.1434288e-01]
 [6.7452437e-01]
 [9.9308181e-01]
 [6.2331635e-01]
 [9.9513638e-01]
 [6.4243406e-02]
 [9.2290598e-01]
 [9.4448054e-01]
 [9.5648557e-0

In [38]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[23  4]
 [ 5 29]]


0.8524590163934426